# CMake generated Testfile for 
# Source directory: F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs
# Build directory: F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/modules/imgcodecs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_imgcodecs "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/bin/opencv_test_imgcodecs.exe" "--gtest_output=xml:opencv_test_imgcodecs.xml")
set_tests_properties(opencv_test_imgcodecs PROPERTIES  LABELS "Main;opencv_imgcodecs;Accuracy" WORKING_DIRECTORY "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/test-reports/accuracy" _BACKTRACE_TRIPLES "F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVUtils.cmake;1707;add_test;F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVModule.cmake;1313;ocv_add_test_from_target;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;166;ocv_add_accuracy_tests;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;0;")
add_test(opencv_perf_imgcodecs "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/bin/opencv_perf_imgcodecs.exe" "--gtest_output=xml:opencv_perf_imgcodecs.xml")
set_tests_properties(opencv_perf_imgcodecs PROPERTIES  LABELS "Main;opencv_imgcodecs;Performance" WORKING_DIRECTORY "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/test-reports/performance" _BACKTRACE_TRIPLES "F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVUtils.cmake;1707;add_test;F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVModule.cmake;1215;ocv_add_test_from_target;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;174;ocv_add_perf_tests;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;0;")
add_test(opencv_sanity_imgcodecs "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/bin/opencv_perf_imgcodecs.exe" "--gtest_output=xml:opencv_perf_imgcodecs.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_imgcodecs PROPERTIES  LABELS "Main;opencv_imgcodecs;Sanity" WORKING_DIRECTORY "F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/test-reports/sanity" _BACKTRACE_TRIPLES "F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVUtils.cmake;1707;add_test;F:/opencv-4.5.2/opencv-4.5.2/cmake/OpenCVModule.cmake;1216;ocv_add_test_from_target;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;174;ocv_add_perf_tests;F:/opencv-4.5.2/opencv-4.5.2/modules/imgcodecs/CMakeLists.txt;0;")
