# CMake generated Testfile for 
# Source directory: F:/opencv-4.5.2/opencv-4.5.2/modules
# Build directory: F:/opencv-4.5.2/build-opencv-4.5.2-Desktop_Qt_5_14_2_MinGW_64_bit-Release/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(".firstpass/calib3d")
subdirs(".firstpass/core")
subdirs(".firstpass/dnn")
subdirs(".firstpass/features2d")
subdirs(".firstpass/flann")
subdirs(".firstpass/gapi")
subdirs(".firstpass/highgui")
subdirs(".firstpass/imgcodecs")
subdirs(".firstpass/imgproc")
subdirs(".firstpass/java")
subdirs(".firstpass/js")
subdirs(".firstpass/ml")
subdirs(".firstpass/objc")
subdirs(".firstpass/objdetect")
subdirs(".firstpass/photo")
subdirs(".firstpass/python")
subdirs(".firstpass/stitching")
subdirs(".firstpass/ts")
subdirs(".firstpass/video")
subdirs(".firstpass/videoio")
subdirs(".firstpass/world")
subdirs(".firstpass/face")
subdirs("core")
subdirs("flann")
subdirs("imgproc")
subdirs("ml")
subdirs("photo")
subdirs("python_tests")
subdirs("dnn")
subdirs("features2d")
subdirs("imgcodecs")
subdirs("videoio")
subdirs("calib3d")
subdirs("highgui")
subdirs("objdetect")
subdirs("stitching")
subdirs("ts")
subdirs("video")
subdirs("face")
subdirs("gapi")
subdirs("java_bindings_generator")
subdirs("js_bindings_generator")
subdirs("objc_bindings_generator")
subdirs("python_bindings_generator")
subdirs("python3")
